### PR TITLE
fix(`semantic-release`): finalise changes from `template-formula`

### PR DESCRIPTION
**Pull request by myii**
* Completes #20

---

@noelmcloughlin These would have been the comments that I added to #20 if I had been able to find time to review that.  Note, `semantic-release` isn't actually working here due to the test failures.  And at the time of submitting this, the actual permissions still need to be fixed (ref: https://freenode.logbot.info/saltstack-formulas/20190625#c2310246).

### CODE REVIEW

**Comment by myii** [comment]
@noelmcloughlin As you may have seen on Slack, the permissions have been fixed and I've forced the release through for #20.  The same will have to be done for all PRs in this formula until the tests are fixed.

**Comment by myii** [comment]
@noelmcloughlin Are you good with these changes so that we're fully complete with `semantic-release` in this formula?

**Review by noelmcloughlin — APPROVED** [review]
Thanks @myii for the hard work. appreciated.

**Comment by myii** [comment]
Thanks, @noelmcloughlin.

**Pull request merged**
